In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.listdir('/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data')

['Corn', 'Cotton', 'Soybeans', 'WinterWheat']

In [ ]:
import os
os.listdir('/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Corn/2017/')

['USDA_Corn_County_2017.csv', '.DS_Store']

In [ ]:
import pandas as pd

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Corn/2017/USDA_Corn_County_2017.csv'
df = pd.read_csv(path)
df.head()

,commodity_desc,reference_period_desc,year,state_ansi,state_name,county_ansi,county_name,asd_code,asd_desc,domain_desc,source_desc,agg_level_desc,"PRODUCTION, MEASURED IN BU","YIELD, MEASURED IN BU / ACRE"
0,CORN,YEAR,2017,1,ALABAMA,1,AUTAUGA,40,BLACK BELT,TOTAL,SURVEY,COUNTY,111000.0,170.8
1,CORN,YEAR,2017,1,ALABAMA,3,BALDWIN,50,COASTAL PLAINS & GULF COAST,TOTAL,SURVEY,COUNTY,907000.0,162.0
2,CORN,YEAR,2017,1,ALABAMA,5,BARBOUR,60,WIREGRASS,TOTAL,SURVEY,COUNTY,298000.0,192.3
3,CORN,YEAR,2017,1,ALABAMA,11,BULLOCK,40,BLACK BELT,TOTAL,SURVEY,COUNTY,108000.0,135.0
4,CORN,YEAR,2017,1,ALABAMA,19,CHEROKEE,20,MOUNTAINS & EASTERN VALLEY,TOTAL,SURVEY,COUNTY,536000.0,146.8

In [ ]:
df.columns

Index(['commodity_desc', 'reference_period_desc', 'year', 'state_ansi',
       'state_name', 'county_ansi', 'county_name', 'asd_code', 'asd_desc',
       'domain_desc', 'source_desc', 'agg_level_desc',
       'PRODUCTION, MEASURED IN BU', 'YIELD, MEASURED IN BU / ACRE'],
      dtype='object')

In [ ]:
df.describe()

,year,state_ansi,county_ansi,asd_code,"PRODUCTION, MEASURED IN BU","YIELD, MEASURED IN BU / ACRE"
count,1481.0,1481.000000,1481.000000,1481.000000,1.481000e+03,1481.000000
mean,2017.0,29.795409,95.518569,50.488184,9.171143e+06,162.070966
std,0.0,13.187090,73.044034,24.950167,1.135035e+07,34.060110
min,2017.0,1.000000,1.000000,10.000000,1.200000e+04,32.600000
25%,2017.0,19.000000,41.000000,30.000000,1.048000e+06,141.700000
50%,2017.0,28.000000,85.000000,50.000000,4.320000e+06,167.100000
75%,2017.0,39.000000,135.000000,70.000000,1.286100e+07,185.700000
max,2017.0,55.000000,800.000000,97.000000,6.827600e+07,246.700000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1481 entries, 0 to 1480
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   commodity_desc                1481 non-null   object
 1   reference_period_desc         1481 non-null   object
 2   year                          1481 non-null   int64
 3   state_ansi                    1481 non-null   int64
 4   state_name                    1481 non-null   object
 5   county_ansi                   1481 non-null   int64
 6   county_name                   1481 non-null   object
 7   asd_code                      1481 non-null   int64
 8   asd_desc                      1481 non-null   object
 9   domain_desc                   1481 non-null   object
 10  source_desc                   1481 non-null   object
 11  agg_level_desc                1481 non-null   object
 12  PRODUCTION, MEASURED IN BU    1481 non-null   float64
 13  YIELD, MEASURED IN BU / ACRE  1481 non-null   float64
dtypes: float64(2), int64(4), object(8)
memory usage: 162.1+ KB

In [ ]:
df.agg_level_desc.unique()

array(['COUNTY'], dtype=object)

In [ ]:
df.domain_desc.unique()

array(['TOTAL'], dtype=object)

In [ ]:
df_corn = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

In [ ]:
df_corn.head()

,commodity_desc,year,state_ansi,state_name,county_ansi,county_name,"YIELD, MEASURED IN BU / ACRE"
0,CORN,2017,1,ALABAMA,1,AUTAUGA,170.8
1,CORN,2017,1,ALABAMA,3,BALDWIN,162.0
2,CORN,2017,1,ALABAMA,5,BARBOUR,192.3
3,CORN,2017,1,ALABAMA,11,BULLOCK,135.0
4,CORN,2017,1,ALABAMA,19,CHEROKEE,146.8

In [ ]:
df_corn = df_corn.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
df_corn.head()

   Crop  Year  State_Code    State  County_Code    County  Yield
0  CORN  2017           1  ALABAMA            1   AUTAUGA  170.8
1  CORN  2017           1  ALABAMA            3   BALDWIN  162.0
2  CORN  2017           1  ALABAMA            5   BARBOUR  192.3
3  CORN  2017           1  ALABAMA           11   BULLOCK  135.0
4  CORN  2017           1  ALABAMA           19  CHEROKEE  146.8

In [ ]:
## Read the Data for Cotton
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Cotton/2017/USDA_Cotton_County_2017.csv'
df = pd.read_csv(path)
df.head()
## Feature Extraction
df_cotton = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN LB / ACRE']]

## Rename the Columns
df_cotton = df_cotton.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN LB / ACRE': 'Yield'
})

In [ ]:
df_cotton.head()

     Crop  Year  State_Code    State  County_Code    County  Yield
0  COTTON  2017           1  ALABAMA            1   AUTAUGA  753.0
1  COTTON  2017           1  ALABAMA            3   BALDWIN  906.0
2  COTTON  2017           1  ALABAMA            5   BARBOUR  818.0
3  COTTON  2017           1  ALABAMA           15   CALHOUN  983.0
4  COTTON  2017           1  ALABAMA           19  CHEROKEE  964.0

In [ ]:
## Read the Data for Soyabean
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Soybeans/2017/USDA_Soybean_County_2017.csv'
df = pd.read_csv(path)


## Feature Extraction
df_soyabean = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

## Rename the Columns
df_soyabean = df_soyabean.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
df_soyabean

          Crop  Year  State_Code      State  County_Code     County  Yield
0     SOYBEANS  2017           1    ALABAMA            3    BALDWIN   42.0
1     SOYBEANS  2017           1    ALABAMA            9     BLOUNT   48.6
2     SOYBEANS  2017           1    ALABAMA           19   CHEROKEE   42.1
3     SOYBEANS  2017           1    ALABAMA           33    COLBERT   48.2
4     SOYBEANS  2017           1    ALABAMA           43    CULLMAN   55.3
...        ...   ...         ...        ...          ...        ...    ...
1348  SOYBEANS  2017          55  WISCONSIN          133   WAUKESHA   44.9
1349  SOYBEANS  2017          55  WISCONSIN          135    WAUPACA   46.8
1350  SOYBEANS  2017          55  WISCONSIN          137   WAUSHARA   42.4
1351  SOYBEANS  2017          55  WISCONSIN          139  WINNEBAGO   47.8
1352  SOYBEANS  2017          55  WISCONSIN          141       WOOD   43.4

[1353 rows x 7 columns]

In [ ]:
## Read the Data for WinterWheat
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/WinterWheat/2017/USDA_WinterWheat_County_2017.csv'
df = pd.read_csv(path)


## Feature Extraction
df_winterwheat = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

## Rename the Columns
df_winterwheat = df_winterwheat.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
df_corn['Yield_kg_ha'] = df_corn['Yield'] * 56 * 1.12085

In [ ]:
df_soyabean['Yield_kg_ha'] = df_soyabean['Yield'] * 60 * 1.12085

In [ ]:
df_winterwheat['Yield_kg_ha'] = df_winterwheat['Yield'] * 60 * 1.12085

In [ ]:
df_cotton['Yield_kg_ha'] = df_cotton['Yield'] * 1.12085

In [ ]:
df_cotton.head()

   Crop  Year  State_Code    State  County_Code    County  Yield  Yield_kg_ha
0  CORN  2017           1  ALABAMA            1   AUTAUGA  170.8   191.441180
1  CORN  2017           1  ALABAMA            3   BALDWIN  162.0   181.577700
2  CORN  2017           1  ALABAMA            5   BARBOUR  192.3   215.539455
3  CORN  2017           1  ALABAMA           11   BULLOCK  135.0   151.314750
4  CORN  2017           1  ALABAMA           19  CHEROKEE  146.8   164.540780

In [ ]:
Yield_2017 = pd.concat(
    [df_corn, df_cotton, df_soyabean, df_winterwheat],
    axis=0,
    ignore_index=True
)

In [ ]:
Yield_2017['Crop'].value_counts()

Crop
CORN        1481
SOYBEANS    1353
WHEAT        857
COTTON       315
Name: count, dtype: int64

In [ ]:
import pandas as pd

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/WinterWheat/2017/USDA_WinterWheat_County_2017.csv'
df = pd.read_csv(path)
df.shape

(857, 14)

In [ ]:
Yield_2017.to_csv(
    "/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2017.csv",
    index=False
)

**2018**

In [ ]:
import pandas as pd

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Corn/2018/USDA_Corn_County_2018.csv'
df = pd.read_csv(path)

df_corn = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_corn = df_corn.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
## Read the Data for Cotton
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Cotton/2018/USDA_Cotton_County_2018.csv'
df = pd.read_csv(path)
df.head()
## Feature Extraction
df_cotton = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN LB / ACRE']]

## Rename the Columns
df_cotton = df_cotton.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN LB / ACRE': 'Yield'
})

In [ ]:
## Read the Data for Cotton
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Soybeans/2018/USDA_Soybean_County_2018.csv'
df = pd.read_csv(path)


## Feature Extraction
df_soyabean = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

## Rename the Columns
df_soyabean = df_soyabean.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
## Read the Data for Cotton
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/WinterWheat/2018/USDA_WinterWheat_County_2018.csv'
df = pd.read_csv(path)


## Feature Extraction
df_winterwheat = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

## Rename the Columns
df_winterwheat = df_winterwheat.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
df_corn['Yield_kg_ha'] = df_corn['Yield'] * 56 * 1.12085

df_soyabean['Yield_kg_ha'] = df_soyabean['Yield'] * 60 * 1.12085

df_winterwheat['Yield_kg_ha'] = df_winterwheat['Yield'] * 60 * 1.12085

df_cotton['Yield_kg_ha'] = df_cotton['Yield'] * 1.12085

In [ ]:
Yield_2018 = pd.concat(
    [df_corn, df_cotton, df_soyabean, df_winterwheat],
    axis=0,
    ignore_index=True
)

In [ ]:
Yield_2018['Crop'].value_counts()

Crop
CORN        1345
SOYBEANS    1181
WHEAT        795
COTTON       319
Name: count, dtype: int64

In [ ]:
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Cotton/2018/USDA_Cotton_County_2018.csv'
df = pd.read_csv(path)
df.shape

(319, 14)

In [ ]:
Yield_2018.to_csv(
    "/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2018.csv",
    index=False
)

**2019**

In [ ]:
import pandas as pd

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Corn/2019/USDA_Corn_County_2019.csv'
df = pd.read_csv(path)

df_corn = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_corn = df_corn.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
## Read the Data for Cotton
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Cotton/2019/USDA_Cotton_County_2019.csv'
df = pd.read_csv(path)
df.head()
## Feature Extraction
df_cotton = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN LB / ACRE']]

## Rename the Columns
df_cotton = df_cotton.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN LB / ACRE': 'Yield'
})

In [ ]:
## Read the Data for Cotton
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Soybeans/2019/USDA_Soybean_County_2019.csv'
df = pd.read_csv(path)


## Feature Extraction
df_soyabean = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

## Rename the Columns
df_soyabean = df_soyabean.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
## Read the Data for Cotton
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/WinterWheat/2019/USDA_WinterWheat_County_2019.csv'
df = pd.read_csv(path)


## Feature Extraction
df_winterwheat = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

## Rename the Columns
df_winterwheat = df_winterwheat.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
df_corn['Yield_kg_ha'] = df_corn['Yield'] * 56 * 1.12085

df_soyabean['Yield_kg_ha'] = df_soyabean['Yield'] * 60 * 1.12085

df_winterwheat['Yield_kg_ha'] = df_winterwheat['Yield'] * 60 * 1.12085

df_cotton['Yield_kg_ha'] = df_cotton['Yield'] * 1.12085

In [ ]:
Yield_2019 = pd.concat(
    [df_corn, df_cotton, df_soyabean, df_winterwheat],
    axis=0,
    ignore_index=True
)

Yield_2019['Crop'].value_counts()

Crop
CORN        1257
SOYBEANS    1098
WHEAT        766
COTTON       326
Name: count, dtype: int64

In [ ]:
Yield_2019.to_csv(
    "/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2019.csv",
    index=False
)

**2020**

In [ ]:
import pandas as pd

## Corn

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Corn/2020/USDA_Corn_County_2020.csv'
df = pd.read_csv(path)

df_corn = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_corn = df_corn.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

## Cotton

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Cotton/2020/USDA_Cotton_County_2020.csv'
df = pd.read_csv(path)
df.head()

df_cotton = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN LB / ACRE']]


df_cotton = df_cotton.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN LB / ACRE': 'Yield'
})

## Soyabean

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Soybeans/2020/USDA_Soybean_County_2020.csv'
df = pd.read_csv(path)

df_soyabean = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_soyabean = df_soyabean.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

## WinterWheat

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/WinterWheat/2020/USDA_WinterWheat_County_2020.csv'
df = pd.read_csv(path)

df_winterwheat = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_winterwheat = df_winterwheat.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
## Standardize the Yiled

df_corn['Yield_kg_ha'] = df_corn['Yield'] * 56 * 1.12085

df_soyabean['Yield_kg_ha'] = df_soyabean['Yield'] * 60 * 1.12085

df_winterwheat['Yield_kg_ha'] = df_winterwheat['Yield'] * 60 * 1.12085

df_cotton['Yield_kg_ha'] = df_cotton['Yield'] * 1.12085

In [ ]:
Yield_2020 = pd.concat(
    [df_corn, df_cotton, df_soyabean, df_winterwheat],
    axis=0,
    ignore_index=True
)

Yield_2020['Crop'].value_counts()

Crop
CORN        1668
SOYBEANS    1471
WHEAT        926
COTTON       323
Name: count, dtype: int64

In [ ]:
path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Corn/2020/USDA_Corn_County_2020.csv'
df = pd.read_csv(path)
df.shape

(1668, 14)

In [ ]:
Yield_2020.to_csv(
    "/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2020.csv",
    index=False
)

**2021**

In [ ]:
import pandas as pd

## Corn

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Corn/2021/USDA_Corn_County_2021.csv'
df = pd.read_csv(path)

df_corn = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_corn = df_corn.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

## Cotton

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Cotton/2021/USDA_Cotton_County_2021.csv'
df = pd.read_csv(path)
df.head()

df_cotton = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN LB / ACRE']]


df_cotton = df_cotton.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN LB / ACRE': 'Yield'
})

## Soyabean

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Soybeans/2021/USDA_Soybean_County_2021.csv'
df = pd.read_csv(path)

df_soyabean = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_soyabean = df_soyabean.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

## WinterWheat

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/WinterWheat/2021/USDA_WinterWheat_County_2021.csv'
df = pd.read_csv(path)

df_winterwheat = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_winterwheat = df_winterwheat.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
## Standardize the Yiled

df_corn['Yield_kg_ha'] = df_corn['Yield'] * 56 * 1.12085

df_soyabean['Yield_kg_ha'] = df_soyabean['Yield'] * 60 * 1.12085

df_winterwheat['Yield_kg_ha'] = df_winterwheat['Yield'] * 60 * 1.12085

df_cotton['Yield_kg_ha'] = df_cotton['Yield'] * 1.12085

In [ ]:
Yield_2021 = pd.concat(
    [df_corn, df_cotton, df_soyabean, df_winterwheat],
    axis=0,
    ignore_index=True
)

Yield_2021['Crop'].value_counts()

Crop
CORN        1472
SOYBEANS    1324
WHEAT        888
COTTON       313
Name: count, dtype: int64

In [ ]:
Yield_2021.to_csv(
    "/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2021.csv",
    index=False
)

**2022**

In [ ]:
import pandas as pd

## Corn

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Corn/2022/USDA_Corn_County_2022.csv'
df = pd.read_csv(path)

df_corn = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_corn = df_corn.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

## Cotton

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Cotton/2022/USDA_Cotton_County_2022.csv'
df = pd.read_csv(path)
df.head()

df_cotton = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN LB / ACRE']]


df_cotton = df_cotton.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN LB / ACRE': 'Yield'
})

## Soyabean

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/Soybeans/2022/USDA_Soybean_County_2022.csv'
df = pd.read_csv(path)

df_soyabean = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_soyabean = df_soyabean.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

## WinterWheat

path = '/content/drive/MyDrive/Crop_Net/USDA Crop Dataset/data/WinterWheat/2022/USDA_WinterWheat_County_2022.csv'
df = pd.read_csv(path)

df_winterwheat = df[['commodity_desc','year','state_ansi','state_name','county_ansi','county_name','YIELD, MEASURED IN BU / ACRE']]

df_winterwheat = df_winterwheat.rename(columns={
    'commodity_desc': 'Crop',
    'year': 'Year',
    'state_ansi': 'State_Code',
    'state_name': 'State',
    'county_name': 'County',
    'county_ansi': 'County_Code',
    'YIELD, MEASURED IN BU / ACRE': 'Yield'
})

In [ ]:
## Standardize the Yiled

df_corn['Yield_kg_ha'] = df_corn['Yield'] * 56 * 1.12085

df_soyabean['Yield_kg_ha'] = df_soyabean['Yield'] * 60 * 1.12085

df_winterwheat['Yield_kg_ha'] = df_winterwheat['Yield'] * 60 * 1.12085

df_cotton['Yield_kg_ha'] = df_cotton['Yield'] * 1.12085

In [ ]:
Yield_2022 = pd.concat(
    [df_corn, df_cotton, df_soyabean, df_winterwheat],
    axis=0,
    ignore_index=True
)

Yield_2022['Crop'].value_counts()

Crop
CORN        1516
SOYBEANS    1368
WHEAT        850
COTTON       305
Name: count, dtype: int64

In [ ]:
Yield_2022.to_csv(
    "/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2022.csv",
    index=False
)

In [ ]:
os.listdir('/content/drive/MyDrive/Crop_Net/processed/')

['USDA_Yield_2017.csv',
 'USDA_Yield_2018.csv',
 'USDA_Yield_2019.csv',
 'USDA_Yield_2021.csv',
 'USDA_Yield_2020.csv',
 'USDA_Yield_2022.csv',
 'USDA_Crop_Yield.csv']

In [ ]:
path = '/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2022.csv'
df = pd.read_csv(path)
df.head()

   Crop  Year  State_Code    State  County_Code    County  Yield  Yield_kg_ha
0  CORN  2022           1  ALABAMA            3   BALDWIN  139.0   8724.69640
1  CORN  2022           1  ALABAMA            5   BARBOUR  159.8  10030.26248
2  CORN  2022           1  ALABAMA            9    BLOUNT  100.4   6301.86704
3  CORN  2022           1  ALABAMA           15   CALHOUN  142.4   8938.10624
4  CORN  2022           1  ALABAMA           19  CHEROKEE  138.5   8693.31260

In [ ]:
df_2017 = pd.read_csv('/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2017.csv')
df_2018 = pd.read_csv('/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2018.csv')
df_2019 = pd.read_csv('/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2019.csv')
df_2020 = pd.read_csv('/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2020.csv')
df_2021 = pd.read_csv('/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2021.csv')
df_2022 = pd.read_csv('/content/drive/MyDrive/Crop_Net/processed/USDA_Yield_2022.csv')

df_all_years = pd.concat(
    [df_2017, df_2018, df_2019, df_2020, df_2021, df_2022],
    axis=0,
    ignore_index=True
)

df_all_years.to_csv(
    "/content/drive/MyDrive/Crop_Net/processed/USDA_Crop_Yield.csv",
    index=False
)

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Crop_Net/processed/USDA_Crop_Yield.csv')
df['Crop'].value_counts()

Crop
CORN        8739
SOYBEANS    7795
WHEAT       5082
COTTON      1901
Name: count, dtype: int64