In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.listdir('/content/drive/MyDrive/Crop_Net/processed')

['WRF-HRRR Computed Dataset',
 'USDA Crop Dataset',
 'Sentinel-2 Imagery',
 'processed']

In [ ]:
import os
os.listdir('/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data')

['2019', '2020', '2017', '2021', '2018', '2022']

In [ ]:
import os
os.listdir('/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data/2017/AL')

['HRRR_01_AL_2017-01.csv',
 'HRRR_01_AL_2017-08.csv',
 'HRRR_01_AL_2017-04.csv',
 'HRRR_01_AL_2017-05.csv',
 'HRRR_01_AL_2017-06.csv',
 'HRRR_01_AL_2017-07.csv',
 'HRRR_01_AL_2017-09.csv',
 'HRRR_01_AL_2017-12.csv',
 'HRRR_01_AL_2017-03.csv',
 'HRRR_01_AL_2017-02.csv',
 'HRRR_01_AL_2017-11.csv',
 'HRRR_01_AL_2017-10.csv']

In [ ]:
import pandas as pd
path = '/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data/2017/AL/HRRR_01_AL_2017-01.csv'

data = pd.read_csv(path)
data.head()

,Year,Month,Day,Daily/Monthly,State,County,FIPS Code,Grid Index,Lat (llcrnr),Lon (llcrnr),...,Max Temperature (K),Min Temperature (K),Precipitation (kg m**-2),Relative Humidity (%),Wind Gust (m s**-1),Wind Speed (m s**-1),U Component of Wind (m s**-1),V Component of Wind (m s**-1),Downward Shortwave Radiation Flux (W m**-2),Vapor Pressure Deficit (kPa)
0,2017,1,1.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,290.994,282.193,42.016,96.5,4.848,5.123,-4.124,2.594,75.0,0.055
1,2017,1,2.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,292.887,289.154,64.633,95.5,5.520,5.616,-4.324,2.171,157.5,0.090
2,2017,1,3.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,292.244,288.020,12.060,90.5,5.229,4.135,0.829,1.566,1211.7,0.188
3,2017,1,4.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,289.156,282.520,0.026,84.3,4.642,4.468,2.568,-2.915,733.0,0.208
4,2017,1,5.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,285.549,274.400,0.001,73.7,3.341,3.105,0.367,-1.449,1013.9,0.284

In [ ]:
data.columns

Index(['Year', 'Month', 'Day', 'Daily/Monthly', 'State', 'County', 'FIPS Code',
       'Grid Index', 'Lat (llcrnr)', 'Lon (llcrnr)', 'Lat (urcrnr)',
       'Lon (urcrnr)', 'Avg Temperature (K)', 'Max Temperature (K)',
       'Min Temperature (K)', 'Precipitation (kg m**-2)',
       'Relative Humidity (%)', 'Wind Gust (m s**-1)', 'Wind Speed (m s**-1)',
       'U Component of Wind (m s**-1)', 'V Component of Wind (m s**-1)',
       'Downward Shortwave Radiation Flux (W m**-2)',
       'Vapor Pressure Deficit (kPa)'],
      dtype='object')

In [ ]:

base_path = '/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data/2017/AL'

files = os.listdir(base_path)

dfs = []

for file in files:
    if file.endswith('.csv'):
        df = pd.read_csv(os.path.join(base_path, file))
        dfs.append(df)

al_2017 = pd.concat(dfs, ignore_index=True)

al_2017.head()

,Year,Month,Day,Daily/Monthly,State,County,FIPS Code,Grid Index,Lat (llcrnr),Lon (llcrnr),...,Max Temperature (K),Min Temperature (K),Precipitation (kg m**-2),Relative Humidity (%),Wind Gust (m s**-1),Wind Speed (m s**-1),U Component of Wind (m s**-1),V Component of Wind (m s**-1),Downward Shortwave Radiation Flux (W m**-2),Vapor Pressure Deficit (kPa)
0,2017,1,1.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,290.994,282.193,42.016,96.5,4.848,5.123,-4.124,2.594,75.0,0.055
1,2017,1,2.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,292.887,289.154,64.633,95.5,5.520,5.616,-4.324,2.171,157.5,0.090
2,2017,1,3.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,292.244,288.020,12.060,90.5,5.229,4.135,0.829,1.566,1211.7,0.188
3,2017,1,4.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,289.156,282.520,0.026,84.3,4.642,4.468,2.568,-2.915,733.0,0.208
4,2017,1,5.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,285.549,274.400,0.001,73.7,3.341,3.105,0.367,-1.449,1013.9,0.284

In [ ]:
al_2017['Avg_Temp_C'] = al_2017['Avg Temperature (K)'] - 273.15

In [ ]:
al_2017.head()

,Year,Month,Day,Daily/Monthly,State,County,FIPS Code,Grid Index,Lat (llcrnr),Lon (llcrnr),...,Min Temperature (K),Precipitation (kg m**-2),Relative Humidity (%),Wind Gust (m s**-1),Wind Speed (m s**-1),U Component of Wind (m s**-1),V Component of Wind (m s**-1),Downward Shortwave Radiation Flux (W m**-2),Vapor Pressure Deficit (kPa),Avg_Temp_C
0,2017,1,1.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,282.193,42.016,96.5,4.848,5.123,-4.124,2.594,75.0,0.055,13.484
1,2017,1,2.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,289.154,64.633,95.5,5.520,5.616,-4.324,2.171,157.5,0.090,17.433
2,2017,1,3.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,288.020,12.060,90.5,5.229,4.135,0.829,1.566,1211.7,0.188,16.491
3,2017,1,4.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,282.520,0.026,84.3,4.642,4.468,2.568,-2.915,733.0,0.208,11.482
4,2017,1,5.0,Daily,ALABAMA,AUTAUGA,1001,0.0,32.340803,-86.917595,...,274.400,0.001,73.7,3.341,3.105,0.367,-1.449,1013.9,0.284,6.441

In [ ]:
daily_county = al_2017.groupby(
    ['FIPS Code','Year','Month','Day']
).agg({
    'Avg_Temp_C': 'mean',
    'Precipitation (kg m**-2)': 'mean',
    'Relative Humidity (%)': 'mean'
}).reset_index()

In [ ]:
yearly_county = daily_county.groupby(
    ['FIPS Code','Year']
).agg({
    'Avg_Temp_C': 'mean',
    'Precipitation (kg m**-2)': 'sum',
    'Relative Humidity (%)': 'mean'
}).reset_index()

In [ ]:
yearly_county = yearly_county.rename(columns={
    'FIPS Code': 'FIPS',
    'Avg_Temp_C': 'Avg_Temp_C',
    'Precipitation (kg m**-2)': 'Total_Rain_mm',
    'Relative Humidity (%)': 'Avg_Humidity'
})

In [ ]:
yearly_county.head()

   FIPS  Year  Avg_Temp_C  Total_Rain_mm  Avg_Humidity
0  1001  2017   18.688329    2594.302067     74.608840
1  1003  2017   20.216143    2746.089951     79.578536
2  1005  2017   19.357939    2084.274033     73.730521
3  1007  2017   18.436129    2352.409375     74.891130
4  1009  2017   17.096745    1983.748321     76.325000

In [ ]:
yearly_county.shape

(67, 5)

In [ ]:
monthly = daily_county.groupby(
    ['FIPS Code','Year','Month']
).agg({
    'Avg_Temp_C':'mean',
    'Precipitation (kg m**-2)':'sum',
    'Relative Humidity (%)':'mean'
}).reset_index()

In [ ]:
monthly.head()

,FIPS Code,Year,Month,Avg_Temp_C,Precipitation (kg m**-2),Relative Humidity (%)
0,1001,2017,1,11.891363,309.266933,75.383871
1,1001,2017,2,13.782586,136.926933,71.508810
2,1001,2017,3,15.310168,98.650667,63.633333
3,1001,2017,4,20.157727,50.458933,66.712667
4,1001,2017,5,21.543338,440.892467,73.386667

In [ ]:
import os
import pandas as pd

base_year_path = '/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data/2017'

states = os.listdir(base_year_path)

monthly_data_list = []

for state in states:

    state_path = os.path.join(base_year_path, state)

    if not os.path.isdir(state_path):
        continue

    monthly_files = os.listdir(state_path)

    dfs = []

    for file in monthly_files:
        if file.endswith('.csv'):
            df = pd.read_csv(os.path.join(state_path, file))
            dfs.append(df)

    if len(dfs) == 0:
        continue

    state_full_year = pd.concat(dfs, ignore_index=True)

    # Convert temperature to Celsius
    state_full_year['Avg_Temp_C'] = state_full_year['Avg Temperature (K)'] - 273.15

    # 🔹 Grid → Daily County
    daily_county = state_full_year.groupby(
        ['FIPS Code','Year','Month','Day']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'mean',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    # 🔹 Daily → Monthly County
    monthly_county = daily_county.groupby(
        ['FIPS Code','Year','Month']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'sum',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    monthly_county = monthly_county.rename(columns={
        'FIPS Code':'FIPS',
        'Precipitation (kg m**-2)':'Total_Rain_mm',
        'Relative Humidity (%)':'Avg_Humidity'
    })

    monthly_data_list.append(monthly_county)

# Combine all states
weather_2017_monthly = pd.concat(monthly_data_list, ignore_index=True)

weather_2017_monthly.head()

    FIPS  Year  Month  Avg_Temp_C  Total_Rain_mm  Avg_Humidity
0  12001  2017      1   15.309211      96.728517     75.909900
1  12001  2017      2   16.819674      50.744586     73.297044
2  12001  2017      3   17.169931      46.813621     66.807119
3  12001  2017      4   21.487587     126.205621     65.627241
4  12001  2017      5   24.069630      93.632276     68.408343

In [ ]:
weather_2017_monthly.shape

(35856, 6)

In [ ]:
import os
import pandas as pd

base_year_path = '/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data/2018'

states = os.listdir(base_year_path)

monthly_data_list = []

for state in states:

    state_path = os.path.join(base_year_path, state)

    if not os.path.isdir(state_path):
        continue

    monthly_files = os.listdir(state_path)

    dfs = []

    for file in monthly_files:
        if file.endswith('.csv'):
            df = pd.read_csv(os.path.join(state_path, file))
            dfs.append(df)

    if len(dfs) == 0:
        continue

    state_full_year = pd.concat(dfs, ignore_index=True)

    # Convert temperature to Celsius
    state_full_year['Avg_Temp_C'] = state_full_year['Avg Temperature (K)'] - 273.15

    # 🔹 Grid → Daily County
    daily_county = state_full_year.groupby(
        ['FIPS Code','Year','Month','Day']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'mean',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    # 🔹 Daily → Monthly County
    monthly_county = daily_county.groupby(
        ['FIPS Code','Year','Month']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'sum',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    monthly_county = monthly_county.rename(columns={
        'FIPS Code':'FIPS',
        'Precipitation (kg m**-2)':'Total_Rain_mm',
        'Relative Humidity (%)':'Avg_Humidity'
    })

    monthly_data_list.append(monthly_county)

# Combine all states
weather_2018_monthly = pd.concat(monthly_data_list, ignore_index=True)

weather_2018_monthly.head()

   FIPS  Year  Month  Avg_Temp_C  Total_Rain_mm  Avg_Humidity
0  5001  2018      1    2.788958     109.637108     72.750480
1  5001  2018      2    9.284847     390.269000     84.454344
2  5001  2018      3   13.205631     189.908865     70.128073
3  5001  2018      4   13.895894     212.133568     70.842342
4  5001  2018      5   24.792530      99.910108     71.289887

(2988, 5)
(2988, 5)

In [ ]:
import os
import pandas as pd

base_year_path = '/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data/2019'

states = os.listdir(base_year_path)

monthly_data_list = []

for state in states:

    state_path = os.path.join(base_year_path, state)

    if not os.path.isdir(state_path):
        continue

    monthly_files = os.listdir(state_path)

    dfs = []

    for file in monthly_files:
        if file.endswith('.csv'):
            df = pd.read_csv(os.path.join(state_path, file))
            dfs.append(df)

    if len(dfs) == 0:
        continue

    state_full_year = pd.concat(dfs, ignore_index=True)

    # Convert temperature to Celsius
    state_full_year['Avg_Temp_C'] = state_full_year['Avg Temperature (K)'] - 273.15

    # 🔹 Grid → Daily County
    daily_county = state_full_year.groupby(
        ['FIPS Code','Year','Month','Day']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'mean',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    # 🔹 Daily → Monthly County
    monthly_county = daily_county.groupby(
        ['FIPS Code','Year','Month']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'sum',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    monthly_county = monthly_county.rename(columns={
        'FIPS Code':'FIPS',
        'Precipitation (kg m**-2)':'Total_Rain_mm',
        'Relative Humidity (%)':'Avg_Humidity'
    })

    monthly_data_list.append(monthly_county)

# Combine all states
weather_2019_monthly = pd.concat(monthly_data_list, ignore_index=True)

weather_2019_monthly.head()

   FIPS  Year  Month  Avg_Temp_C  Total_Rain_mm  Avg_Humidity
0  6001  2019      1   10.160490      74.152700     70.241290
1  6001  2019      2    7.945689     127.885600     72.051548
2  6001  2019      3   10.894204      55.649000     68.417634
3  6001  2019      4   14.530230       7.993733     65.961000
4  6001  2019      5   13.934370      36.958767     71.946237

In [ ]:
import os
import pandas as pd

base_year_path = '/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data/2020'

states = os.listdir(base_year_path)

monthly_data_list = []

for state in states:

    state_path = os.path.join(base_year_path, state)

    if not os.path.isdir(state_path):
        continue

    monthly_files = os.listdir(state_path)

    dfs = []

    for file in monthly_files:
        if file.endswith('.csv'):
            df = pd.read_csv(os.path.join(state_path, file))
            dfs.append(df)

    if len(dfs) == 0:
        continue

    state_full_year = pd.concat(dfs, ignore_index=True)

    # Convert temperature to Celsius
    state_full_year['Avg_Temp_C'] = state_full_year['Avg Temperature (K)'] - 273.15

    # 🔹 Grid → Daily County
    daily_county = state_full_year.groupby(
        ['FIPS Code','Year','Month','Day']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'mean',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    # 🔹 Daily → Monthly County
    monthly_county = daily_county.groupby(
        ['FIPS Code','Year','Month']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'sum',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    monthly_county = monthly_county.rename(columns={
        'FIPS Code':'FIPS',
        'Precipitation (kg m**-2)':'Total_Rain_mm',
        'Relative Humidity (%)':'Avg_Humidity'
    })

    monthly_data_list.append(monthly_county)

# Combine all states
weather_2020_monthly = pd.concat(monthly_data_list, ignore_index=True)

weather_2020_monthly.head()

   FIPS  Year  Month  Avg_Temp_C  Total_Rain_mm  Avg_Humidity
0  8001  2020      1    0.686022       4.264067     49.237849
1  8001  2020      2   -1.698047      24.903200     58.137471
2  8001  2020      3    5.061084      63.013300     58.028172
3  8001  2020      4    7.809962      29.865533     49.107889
4  8001  2020      5   15.039634      28.820600     53.691183

In [ ]:
import os
import pandas as pd

base_year_path = '/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data/2021'

states = os.listdir(base_year_path)

monthly_data_list = []

for state in states:

    state_path = os.path.join(base_year_path, state)

    if not os.path.isdir(state_path):
        continue

    monthly_files = os.listdir(state_path)

    dfs = []

    for file in monthly_files:
        if file.endswith('.csv'):
            df = pd.read_csv(os.path.join(state_path, file))
            dfs.append(df)

    if len(dfs) == 0:
        continue

    state_full_year = pd.concat(dfs, ignore_index=True)

    # Convert temperature to Celsius
    state_full_year['Avg_Temp_C'] = state_full_year['Avg Temperature (K)'] - 273.15

    # 🔹 Grid → Daily County
    daily_county = state_full_year.groupby(
        ['FIPS Code','Year','Month','Day']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'mean',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    # 🔹 Daily → Monthly County
    monthly_county = daily_county.groupby(
        ['FIPS Code','Year','Month']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'sum',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    monthly_county = monthly_county.rename(columns={
        'FIPS Code':'FIPS',
        'Precipitation (kg m**-2)':'Total_Rain_mm',
        'Relative Humidity (%)':'Avg_Humidity'
    })

    monthly_data_list.append(monthly_county)

# Combine all states
weather_2021_monthly = pd.concat(monthly_data_list, ignore_index=True)

weather_2021_monthly.head()

   FIPS  Year  Month  Avg_Temp_C  Total_Rain_mm  Avg_Humidity
0  6001  2021      1    9.675142      63.648433     67.175699
1  6001  2021      2   10.546643      19.416833     60.793690
2  6001  2021      3   10.250587      20.204500     60.768602
3  6001  2021      4   12.922462       2.251800     62.268556
4  6001  2021      5   15.491527       0.169867     60.706774

In [ ]:
import os
import pandas as pd

base_year_path = '/content/drive/MyDrive/Crop_Net/WRF-HRRR Computed Dataset/data/2022'

states = os.listdir(base_year_path)

monthly_data_list = []

for state in states:

    state_path = os.path.join(base_year_path, state)

    if not os.path.isdir(state_path):
        continue

    monthly_files = os.listdir(state_path)

    dfs = []

    for file in monthly_files:
        if file.endswith('.csv'):
            df = pd.read_csv(os.path.join(state_path, file))
            dfs.append(df)

    if len(dfs) == 0:
        continue

    state_full_year = pd.concat(dfs, ignore_index=True)

    # Convert temperature to Celsius
    state_full_year['Avg_Temp_C'] = state_full_year['Avg Temperature (K)'] - 273.15

    # 🔹 Grid → Daily County
    daily_county = state_full_year.groupby(
        ['FIPS Code','Year','Month','Day']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'mean',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    # 🔹 Daily → Monthly County
    monthly_county = daily_county.groupby(
        ['FIPS Code','Year','Month']
    ).agg({
        'Avg_Temp_C':'mean',
        'Precipitation (kg m**-2)':'sum',
        'Relative Humidity (%)':'mean'
    }).reset_index()

    monthly_county = monthly_county.rename(columns={
        'FIPS Code':'FIPS',
        'Precipitation (kg m**-2)':'Total_Rain_mm',
        'Relative Humidity (%)':'Avg_Humidity'
    })

    monthly_data_list.append(monthly_county)

# Combine all states
weather_2022_monthly = pd.concat(monthly_data_list, ignore_index=True)

weather_2022_monthly.head()

    FIPS  Year  Month  Avg_Temp_C  Total_Rain_mm  Avg_Humidity
0  11001  2022      1    0.436710        106.544     63.364516
1  11001  2022      2    4.418357         52.753     70.221429
2  11001  2022      3    8.978097         76.378     59.383871
3  11001  2022      4   13.054367         62.587     58.510000
4  11001  2022      5   19.096935         74.957     71.983871

In [ ]:
print(weather_2017_monthly.shape)
print(weather_2018_monthly.shape)
print(weather_2019_monthly.shape)
print(weather_2020_monthly.shape)
print(weather_2021_monthly.shape)
print(weather_2022_monthly.shape)

(35856, 6)
(35856, 6)
(35856, 6)
(35856, 6)
(35856, 6)
(35855, 6)

In [ ]:
weather_data_monthly = pd.concat(
    [weather_2017_monthly, weather_2018_monthly, weather_2019_monthly, weather_2020_monthly, weather_2021_monthly, weather_2022_monthly],
    axis=0,
    ignore_index=True
)

In [ ]:
weather_data_monthly.shape

(215135, 6)

In [ ]:
weather_data_monthly['Year'].value_counts()

Year
2017    35856
2018    35856
2019    35856
2020    35856
2021    35856
2022    35855
Name: count, dtype: int64

In [ ]:
weather_data_monthly.duplicated(
    subset=['FIPS','Year']
).sum()

np.int64(197207)

In [ ]:
weather_data_monthly.to_csv('/content/drive/MyDrive/Crop_Net/processed/Weather_data_monthly.csv', index=False)

In [ ]:
os.listdir('/content/drive/MyDrive/Crop_Net/processed/weather_data')

['Weather_data_2017.csv',
 'Weather_data_2018.csv',
 'Weather_data_2019.csv',
 'Weather_data_2020.csv',
 'Weather_data_2021.csv',
 'Weather_data_2022.csv',
 'Weather_data_2017_monthly.csv',
 'Weather_data_2018_monthly.csv',
 'Weather_data_2019_monthly.csv',
 'Weather_data_2020_monthly.csv',
 'Weather_data_2021_monthly.csv',
 'Weather_data_2022_monthly.csv']

In [ ]:
new_folder_path = '/content/drive/MyDrive/Crop_Net/processed/weather_data'
os.makedirs(new_folder_path, exist_ok=True)

In [ ]:
weather_2017_monthly.to_csv('/content/drive/MyDrive/Crop_Net/processed/weather_data/Weather_data_2017_monthly.csv')
weather_2018_monthly.to_csv('/content/drive/MyDrive/Crop_Net/processed/weather_data/Weather_data_2018_monthly.csv')
weather_2019_monthly.to_csv('/content/drive/MyDrive/Crop_Net/processed/weather_data/Weather_data_2019_monthly.csv')
weather_2020_monthly.to_csv('/content/drive/MyDrive/Crop_Net/processed/weather_data/Weather_data_2020_monthly.csv')
weather_2021_monthly.to_csv('/content/drive/MyDrive/Crop_Net/processed/weather_data/Weather_data_2021_monthly.csv')
weather_2022_monthly.to_csv('/content/drive/MyDrive/Crop_Net/processed/weather_data/Weather_data_2022_monthly.csv')